import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header titleButton="How it works" titleLink="Sign in" />
        <main className="mx-auto max-w-5xl ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
